const actionType = {
  INIT_PRODUCTS: 'INIT_PRODUCTS',
  SET_ALL_PRODUCTS: 'SET_ALL_PRODUCTS',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  SET_POPULAR_PRODUCTS: 'SET_POPULAR_PRODUCTS',
  GET_POPULAR_PRODUCTS: 'GET_POPULAR_PRODUCTS',
  SET_NEW_PRODUCTS: 'SET_NEW_PRODUCTS',
  GET_NEW_PRODUCTS: 'GET_NEW_PRODUCTS',
  SET_FILTERS: 'SET_FILTERS',
  SET_SORT: 'SET_SORT',
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
  SET_SEARCH: 'SET_SEARCH',
};

export default actionType;
